Do not include spotless-lib and spotless-lib-extra in shadowJar
Only bundle com.diffplug.durian:* and org.eclipse.jgit:org.eclipse.jgit
Relocate JGit with spotless.shadow prefix.

This breaks most tests in plugin-gradle with:

  java.lang.NoClassDefFoundError: com/diffplug/spotless/Jvm