Fixed maven plugin dependency on plexus-resources
POMs for publishing to maven central are generated using
`./gradlew generatePomFileForPluginMavenPublication` command. Generated
POMs include compile dependencies from gradle build scripts with
`<scope>compile</scope>`. Dependency `org.codehaus.plexus:plexus-resources:1.0.1`
was declared as compile-only in the gradle build script. This made POM
generation skip it. So published plugin did not specify all needed
dependencies in it's POM, which resulted in `NoClassDefFoundError`
errors.

This commit fixes the problem by declaring `plexus-resources` dependency
with compile scope. Generated POM then contains it as a correct
scope-compile dependency.